name: Sync to Hugging Face
on:
  push:
    branches: [main] # Or your default branch name
  workflow_dispatch: # Allows manual trigger

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true # Crucial if your repo uses LFS
      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "Error: HF_TOKEN is not set in GitHub secrets."
            exit 1
          fi
          git config --global user.email "amosquety@example.com"
          git config --global user.name "AmosQuety"
          git remote add huggingface https://oauth2:$HF_TOKEN@huggingface.co/spaces/AmosQuety/biometric-brain
          git push --force huggingface HEAD:main